### ISSUE TITLE
Invalid example source in README.rst

### ISSUE THREAD

**Issue by sriv1211** [yougov/paradocx#3]
`See the source for a trivial example of usage.` points to the old bitbucket directory.

In addition the .xml files using the `load_template` [function](https://github.com/yougov/paradocx#object-model-and-advanced-usage) are not in this repository, but would be useful to folow the advanced usage example.

**Comment by jaraco** [comment]
Thanks for the report!

I've updated the readme to correct the broken link.

As for providing sample XML files for the parts of the file, that's something that doesn't exist readily. Someone would have to prepare samples. Presumably, it could be readily done by using MS Word or compatible system for generating a docx file and then extracting its zip contents.

I won't have time to create such samples, but if you do, please do consider contributing those back to the project in a /samples or /examples directory. Any contributions will be appreciated.
