### ISSUE TITLE
Is it possible to have a way to load a docx ?

### ISSUE THREAD

**Issue by lu-zero** [yougov/paradocx#5]
From what I could see openpack has a mean to load the docx, but the main Document class has no `load` or a constructor to directly populate itself.

**Comment by jaraco** [comment]
Yes. See [the tests](https://github.com/yougov/paradocx/blob/e525b3cdb54af6896fc941ef03c2be4275443bcf/test/test_sample.py#L14-L21). You can use `from_stream` to open the doc from a stream of bytes or `from_file` to open a filename and read it.
